services:
  api:
    image: ghcr.io/parjanya-kumar-arya-github/csot-w3-starter:latest
    networks:
      - csot-net
    volumes:
      - sqlite_data:/app/instance  
    restart: always

  web:
    image: nginx:alpine
    networks:
      - csot-net
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"  
    depends_on:
      - api
    restart: always

networks:
  csot-net:
    driver: bridge

volumes:
  sqlite_data: